//! Differential test against the Go verifier.
//!
//! The corpus at `testdata/differential-corpus.jsonl` is generated by the Go
//! `cmd/gen-corpus` tool, which presigns URLs with the MinIO SDK, mutates them,
//! and records the Go verifier's decision for every case. This test replays the
//! corpus through the Rust verifier core using the identical fixed
//! configuration and asserts that both the allow/deny outcome and the stable
//! reason string match Go exactly.
//!
//! Regenerate the corpus with `go run ./cmd/gen-corpus` from the repo root.

use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::Deserialize;
use sigv4_verifier::{Credential, Settings, Verifier};

#[derive(Deserialize)]
struct CorpusLine {
    name: String,
    method: String,
    uri: String,
    host: String,
    now_unix: i64,
    allowed: bool,
    reason: String,
}

// These constants mirror cmd/gen-corpus/main.go byte-for-byte. Keep both sides
// in sync when changing the fixed configuration.
const HOST_ASSETS: &str = "assets.example.com";
const HOST_CDN: &str = "cdn.example.com";

const KEY_UNRESTRICTED: &str = "AKIAUNRESTRICTED";
const KEY_DISABLED: &str = "AKIADISABLED";
const KEY_HOST_ONLY: &str = "AKIAHOSTONLY";
const KEY_GET_ONLY: &str = "AKIAGETONLY";
const KEY_PREFIX: &str = "AKIAPREFIX";
const KEY_SHORT_EXP: &str = "AKIASHORTEXP";

const SECRET_UNRESTRICTED: &str = "unrestricted-secret-000";
const SECRET_DISABLED: &str = "disabled-secret-111";
const SECRET_HOST_ONLY: &str = "hostonly-secret-222";
const SECRET_GET_ONLY: &str = "getonly-secret-333";
const SECRET_PREFIX: &str = "prefix-secret-444";
const SECRET_SHORT_EXP: &str = "shortexp-secret-555";

fn fixed_settings() -> Settings {
    Settings {
        allowed_clock_skew: Duration::from_secs(60),
        default_max_expires: Duration::from_secs(60 * 60),
        supported_methods: vec!["GET".to_string(), "HEAD".to_string()],
        supported_service: "s3".to_string(),
    }
}

fn fixed_credentials() -> Vec<Credential> {
    vec![
        // Unrestricted-style: enabled with explicit (broad) allow lists.
        Credential {
            access_key: KEY_UNRESTRICTED.to_string(),
            secret_key: SECRET_UNRESTRICTED.to_string(),
            enabled: true,
            max_expires: Duration::ZERO,
            allowed_hosts: vec![HOST_ASSETS.to_string(), HOST_CDN.to_string()],
            allowed_methods: vec!["GET".to_string(), "HEAD".to_string()],
            allowed_prefixes: vec![b"/".to_vec()],
        },
        // Disabled: reached only through the enabled gate.
        Credential {
            access_key: KEY_DISABLED.to_string(),
            secret_key: SECRET_DISABLED.to_string(),
            enabled: false,
            max_expires: Duration::ZERO,
            allowed_hosts: Vec::new(),
            allowed_methods: Vec::new(),
            allowed_prefixes: Vec::new(),
        },
        // Host-restricted to assets only.
        Credential {
            access_key: KEY_HOST_ONLY.to_string(),
            secret_key: SECRET_HOST_ONLY.to_string(),
            enabled: true,
            max_expires: Duration::ZERO,
            allowed_hosts: vec![HOST_ASSETS.to_string()],
            allowed_methods: Vec::new(),
            allowed_prefixes: Vec::new(),
        },
        // Method-restricted to GET only.
        Credential {
            access_key: KEY_GET_ONLY.to_string(),
            secret_key: SECRET_GET_ONLY.to_string(),
            enabled: true,
            max_expires: Duration::ZERO,
            allowed_hosts: Vec::new(),
            allowed_methods: vec!["GET".to_string()],
            allowed_prefixes: Vec::new(),
        },
        // Prefix-restricted to /public-bucket/public without a trailing slash.
        Credential {
            access_key: KEY_PREFIX.to_string(),
            secret_key: SECRET_PREFIX.to_string(),
            enabled: true,
            max_expires: Duration::ZERO,
            allowed_hosts: Vec::new(),
            allowed_methods: Vec::new(),
            allowed_prefixes: vec![b"/public-bucket/public".to_vec()],
        },
        // Short max expiry (60s).
        Credential {
            access_key: KEY_SHORT_EXP.to_string(),
            secret_key: SECRET_SHORT_EXP.to_string(),
            enabled: true,
            max_expires: Duration::from_secs(60),
            allowed_hosts: Vec::new(),
            allowed_methods: Vec::new(),
            allowed_prefixes: Vec::new(),
        },
    ]
}

fn system_time_from_unix(seconds: i64) -> SystemTime {
    if seconds >= 0 {
        UNIX_EPOCH + Duration::from_secs(seconds as u64)
    } else {
        UNIX_EPOCH - Duration::from_secs((-seconds) as u64)
    }
}

#[test]
fn matches_go_verifier_decisions() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/testdata/differential-corpus.jsonl"
    );
    let contents =
        std::fs::read_to_string(path).unwrap_or_else(|err| panic!("read corpus {path}: {err}"));

    let verifier = Verifier::new(fixed_settings(), fixed_credentials())
        .expect("fixed verifier config is valid");

    let mut count = 0;
    let mut prefix_boundary_count = 0;
    for (index, raw) in contents.lines().enumerate() {
        let raw = raw.trim();
        if raw.is_empty() {
            continue;
        }
        let line: CorpusLine = serde_json::from_str(raw)
            .unwrap_or_else(|err| panic!("parse corpus line {}: {err}", index + 1));

        let expected_prefix_boundary_result = match line.name.as_str() {
            "valid_prefix_exact" | "valid_prefix_child_get" | "valid_prefix_child_head" => {
                Some(true)
            }
            "prefix_policy_adjacent_sibling_denied" => Some(false),
            _ => None,
        };
        if let Some(expected) = expected_prefix_boundary_result {
            assert_eq!(
                line.allowed, expected,
                "case {:?}: Go corpus violates the prefix-boundary contract",
                line.name,
            );
            prefix_boundary_count += 1;
        }

        let result = verifier.verify(
            &line.method,
            line.uri.as_bytes(),
            &line.host,
            system_time_from_unix(line.now_unix),
        );

        assert_eq!(
            result.allowed, line.allowed,
            "case {:?}: Go allowed={} but Rust allowed={} (reason {:?})",
            line.name, line.allowed, result.allowed, result.reason,
        );
        assert_eq!(
            result.reason, line.reason,
            "case {:?}: Go reason={:?} but Rust reason={:?}",
            line.name, line.reason, result.reason,
        );
        count += 1;
    }

    assert!(
        count >= 150,
        "expected at least 150 corpus cases, got {count}"
    );
    assert_eq!(
        prefix_boundary_count, 4,
        "expected exact, child GET/HEAD, and adjacent-sibling prefix-boundary cases"
    );
}
